### ISSUE TITLE
This breaks Find Results in ST3 dev builds

### ISSUE THREAD

**Issue by canoeberry** [titoBouzout/FindResultsApplyChanges#10]
Has anybody noticed that? I have to disable this plugin or I cannot use Find Next or double click on items in the results.

**Comment by titoBouzout** [comment]
that's intentionally

**Comment by canoeberry** [comment]
Oh. But then how can I use Find Results the normal way and only use your added functionality when I want it? I am sure this used to work.

**Comment by titoBouzout** [comment]
this package allows to edit the find results and hit ctrl+s to save all
changes to the modified files. If I double click a word to edit, the file
open, I don't want that, what I want is to select the word. So I disabled
that functionality. I open file with ALT+D using open include package.
unfortunately this change breaks find next.

On Thu, 8 Oct 2015 17:37 Jonathan Payne <notifications@github.com> wrote:

> Oh. But then how can I use Find Results the normal way and only use your
> added functionality when I want it? I am sure this used to work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/titoBouzout/FindResultsApplyChanges/issues/10#issuecomment-146665245>
> .
>
-- 

__
Tito

**Comment by canoeberry** [comment]
I humbly disagree with your choices here. But I will close since this is intentional.

**Comment by titoBouzout** [comment]
okei, I would accept a pull request to add a preference to avoid that

On Thu, 8 Oct 2015 17:45 Jonathan Payne <notifications@github.com> wrote:

> Closed #10
> <https://github.com/titoBouzout/FindResultsApplyChanges/issues/10>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/titoBouzout/FindResultsApplyChanges/issues/10#event-430720450>
> .
>
-- 

__
Tito

**Comment by pomeh** [comment]
@titoBouzout I agree with @canoeberry on this, would be nice to keep the double click behavior.

Looking at the code, I can't see where this behavior is disabled. Maybe this ? :

```python
class FindResultsApplyChangesEventListener(sublime_plugin.EventListener):

	def on_activated(self, view):
		if view.name() == 'Find Results':
			view.settings().set("result_file_regex", '')
			view.settings().set("result_line_regex", '')
```

What do you think if a setting like `disable_double_click` (default value `true`) is added ? This would lead to something like this:

```python
class FindResultsApplyChangesEventListener(sublime_plugin.EventListener):

	def on_activated(self, view):
		if view.name() == 'Find Results' and view.settings().get('disable_double_click', True):
			view.settings().set("result_file_regex", '')
			view.settings().set("result_line_regex", '')
```

What are your though with this ?

**Comment by FichteFoll** [comment]
@pomeh, yes, this is exactly it.

**Comment by pomeh** [comment]
Ok nice. I will look into it and do a pull request for that then :)

**Comment by canoeberry** [comment]
The amazing thing is, Today, of all days, I thought about this again for the first time since we had this chat.

**Comment by ilearnio** [comment]
I found some sort of a solution to this issue. It appears that [open-include](https://github.com/titoBouzout/Open-Include) package allows using Alt+D to jump to any line of search results. Which for me is even nicer alternative to double-click

**Comment by titoBouzout** [comment]
Exactly :)
