### ISSUE TITLE
Exclude a directory but keep some of it's subdirectories?

### ISSUE THREAD

**Issue by ilearnio** [titoBouzout/FindResultsApplyChanges#12]
Hey! I was looking for a way to skip directories from search (cmd+p and Find in files) for ages! Just found your plugin and it made me so happy! I have 33000+ files in my project but after I excluded some of the directories from the search, it feels like I have just 400, bellissimo :)!

There is one more thing for me to set up for a super keen ST workflow. I have a `node_modules` directory with many packages (around 30k files) and I need to exclude all the stuff it has except for some specific packages. Is there a way to do so with your package?

Thanks!

**Comment by titoBouzout** [comment]
If you right click that directory and select "find and replace" that directory is not excluded, because all searches that will trigger a "skip/exclusion" of the selected directory/file are removed from the exclusion list.

**Comment by ilearnio** [comment]
Do you mean right-click on `node_modules` directory? Currently, I am doing it that way, but still it searches in every of 30k files which give lots of redundant results, so it's nearly impossible to find anything (unless I know exactly how the file looks like in order to make a more specific search query). It would be nice to have an ability to do something like this

```
"binary_file_patterns": [
  "node_modules/**",
  "!node_modules/my-package",
  "!node_modules/thirdparty-package"
]
```

So it's probably a feature to consider

**Comment by titoBouzout** [comment]
I mean to right click node_modules/thirdparty-package

On Tue, Mar 8, 2016, 11:33 Nikita Gavrilov <notifications@github.com> wrote:

> Do you mean right-click on node_modules directory? Currently, I am doing
> it that way, but still it searches in every of 30k files which give lots of
> redundant results, so it's nearly impossible to find anything (unless I
> know exactly how the file looks like in order to make a more specific
> search query). It would be nice to have an ability to do something like this
>
> "binary_file_patterns": [
>   "node_modules/**",
>   "!node_modules/my-package",
>   "!node_modules/thirdparty-package"
> ]
>
> So it's probably a feature to consider
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/titoBouzout/FindResultsApplyChanges/issues/12#issuecomment-193804996>
> .
>
-- 

__
Tito

**Comment by ilearnio** [comment]
Sometimes I don't know which package is it. For example, there might be a `console.log` or some `require(...)` somewhere I left in the project but don't remember where exactly... in some package or in a project's sources

**Comment by titoBouzout** [comment]
I understand you request, but is not possible, however with sidebar
enanchrmentts you can select fours or more folders and search, more
explicit than that idk..

On Tue, Mar 8, 2016, 11:41 Nikita Gavrilov <notifications@github.com> wrote:

> Sometimes I don't know which package is it. For example, there might be a
> console.log or some require(...) somewhere I left in the project but
> don't remember where exactly... in some package or in a project's sources
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/titoBouzout/FindResultsApplyChanges/issues/12#issuecomment-193808835>
> .
>
-- 

__
Tito

**Comment by ilearnio** [comment]
You're right! Didn't knew about such feature. I will definitely use that! Thank you very much! I guess I can close this issue
