### ISSUE TITLE
Package Suppresses 'Where' History

### ISSUE THREAD

**Issue by jesgundy** [titoBouzout/FindResultsApplyChanges#13]
Typically when you trigger the find panel in sublime, it remembers the last value you had placed in the 'Where' field. This is really helpful to search inside a project without needing to edit that field each time. Currently the package seems to suppress. 

I believe the offending code is here: https://github.com/titoBouzout/FindResultsApplyChanges/blob/master/FindExcludePatterns.py#L16-L34

The code looks for an explicit `where` argument, and if it doesn't find it, it creates one with the exclude params. I think this overwrites the history behavior. It would be great if the package leveraged the most recent `where_history` entry in the `[project].sublime-workspace` file.

As a stop gap I've updated my "Find and Replace" key binding to pass in my current project, excluding a few relevant folders:

`{ "keys": ["super+shift+f"], "command": "show_panel", "args": {"panel": "find_in_files", "where": "<project>,-dist/,-node_modules/"} },`

Great plugin! Cheers.

**Comment by jimoldham** [comment]
I believe the "Find Exclude Patterns" functionality that was merged into this package is the culprit. It is setting the default 'where' argument to the exclude list like you mention. My question is: is that even necessary? From everything I could find the "binary_exlude_patterns" are automatically excluded from the search. Why verbosely list them and convolute the 'where' search field?

**Comment by titoBouzout** [comment]
Because binary_exlude_patterns simply does not work

**Comment by jimoldham** [comment]
Why do you say that 'binary_exclude_patterns' simply does not work? I'm using Sublime Text 3 (build 3114) and I just did a quick test. I added "*.sql" to the 'binary_file_patterns' property in my 'Preferences' -> 'Settings - User' config file and then performed a search for a phrase that is in many .sql files in my project. It worked just fine. No find results were returned for any .sql files.

**Comment by titoBouzout** [comment]
binary_file_patterns :["jquery-2.2.1.4.min.js", "*.min.js"]

search and will give results there are more examples
