### ISSUE TITLE
Plugin disables the ability to open files by double clicking the line?

### ISSUE THREAD

**Issue by adamt19** [titoBouzout/FindResultsApplyChanges#9]
I saw in your forums that one person (one) mentioned a preference to disable the default ST behavior of opening files to a line when that line is double-clicked in the find results view.

Was this disabled per his request?

Can I use this package and maintain the default behavior?

Sometimes Find Results doesn't show me enough lines below the found string to display what I'm trying to edit, and in that case I need to use Find to open the file and edit it directly.

**Comment by titoBouzout** [comment]
Hi you cannot use this package and maintain default behavior. you can
install open include package and open with alt+d
